### ISSUE TITLE
Not visible at app store

### ISSUE THREAD

**Issue by burner-** [WARP-LAB/files_3dmodelviewer#1]
Looks that this app is not visible at appstore.

**Comment by kroko** [comment]
Yep, because NC has not yet issued certificate https://github.com/nextcloud/app-certificate-requests/pull/580 , step needed as per docs [Publishing Apps on the App Store](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#publishing-apps-on-the-app-store), the link in the readme is placeholder based on app id.

**Comment by kroko** [comment]
CRT was issued, app published <https://apps.nextcloud.com/apps/files_3dmodelviewer> 🥳
