### ISSUE TITLE
Viewer not opening

### ISSUE THREAD

**Issue by anomaly256** [WARP-LAB/files_3dmodelviewer#2]
## Describe the bug

Preview doesn't open, Nextcloud just downloads the file when clicked

## To Reproduce

1. Install app
2. Upload .obj or .stl files
3. Browse to them in the Files app
4. Click on them

## Expected behavior

The 3d viewer preview screen to display

## Desktop (please complete the following information)

- OS: Macos (Apple Silicon)
- Browser Chrome, Safari
- Version Nextcloud 25.0.4

## Browser log

```sh
GET https://[redacted]/custom_apps/files_3dmodelviewer/js/files_3dmodelviewer.js?v=841b80fe-19 net::ERR_ABORTED 404
Refused to execute script from 'https://[redacted]/custom_apps/files_3dmodelviewer/js/files_3dmodelviewer.js?v=841b80fe-19' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by anomaly256** [comment]
Fyi the app store is now telling me: `Error: This app cannot be enabled because it makes the server unstable`

**Comment by kroko** [comment]
1. How did you install the app - via app store or manually unpacking the tar.gz and putting it into place?
2. Browser log mentions `custom_apps` in the path. Do you mind sharing your value for key `apps_path` as set in `config/config.php` file? Ref: [Using custom app directories](https://docs.nextcloud.com/server/latest/admin_manual/apps_management.html#using-custom-app-directories)
3. App assumes it is installed in `apps` as it is place it should be installed in standard NC installations.
4. Your browser logs tells that NC is trying to load it from `custom_apps` -> the script is not there -> NC does rewrite to HTML as it does with non existing resources -> browser sees that instead of js it receives `text/html` and thing dies.

**Comment by anomaly256** [comment]
1) via the app store on a new install
2-5) I'm reinstalling a clean instance as I found other issues with this one that had been upgraded and upgraded over many years.  I'll let you know if the problem exists in that new environment or close this issue if not

**Comment by kroko** [comment]
Ok. I'd suggest to not use custom `apps_paths` config, unless there is some specific reason you have to (and if so, then at this moment you would need to clone the repo and make changes to all `generateUrl` calls in `src/js`). As said before, this app assumes install in default NC app location that has URL `/apps`. Meanwhile I have opened a question, so that custom paths might also be supported https://github.com/nextcloud/nextcloud-router/issues/450

**Comment by anomaly256** [comment]
I honestly don't think I ever changed apps_path and I can't explain why it would have ended up there.

I've just now hit a nice landmine in nextcloud's official docker images though while trying to start with a fresh install

      https://github.com/nextcloud/docker/issues/1925

It's now a much fresher install than anticipated.  I'll test your app again once the rsyncing of 15 years of family photos and movies from a slow NAS completes

**Comment by anomaly256** [comment]
Working on the fresh install 👍, closing this issue

**Comment by kroko** [comment]
Meanwhile [support was for custom app install location was added](https://github.com/WARP-LAB/files_3dmodelviewer/commit/fe254e2b4faba363a2323cacff467a16505c8144) and pushed new 0.0.6 release, thus statements made in https://github.com/WARP-LAB/files_3dmodelviewer/issues/2#issuecomment-1443481808 are now untrue.
